/* JS */ gapi.loaded_4(function(_){var window=this;
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var AG=function(a,b,c,d,e){this.width=a;this.height=b;this.Cm=c;this.Dm=d;this.opacity=e},BG=function(a,b,c,d){return new AG(void 0==b?a.width:b,void 0==c?a.height:c,a.Cm,a.Dm,void 0==d?a.opacity:d)};AG.prototype.equals=function(a){return this.width==a.width&&this.height==a.height&&this.Cm==a.Cm&&this.Dm==a.Dm&&this.opacity==a.opacity};
AG.prototype.interpolate=function(a,b){var c=1-b;return new AG(Math.round(this.width*c+a.width*b),Math.round(this.height*c+a.height*b),Math.round(this.Cm*c+a.Cm*b),Math.round(this.Dm*c+a.Dm*b),this.opacity*c+a.opacity*b)};
_.CG=function(a){_.ms.call(this,a);this.ya=new _.gs(this)};_.fj(_.CG,_.os);_.h=_.CG.prototype;
_.h.create=function(){var a=Number(this.$j(200,"widgetWidth","width")),b=Number(this.$j(100,"widgetHeight","height")),c=this.$j("auto","corner"),d=this.$j({},"menuCss"),e=this.$j(!0,"hideOnClick");this.zq=!!this.$j(!0,"hideOnLeave");this.OD=!!this.$j((0,_.$y)(),"useCss3Transition");this.mQ=!!this.$j(!0,"allowOffset");var f=document.createElement("div");this.Aa=f;var g=this.yh();g.parentNode.appendChild(f);var k=document.createElement("div");this.Am=k;f.appendChild(k);d.position="absolute";d.width=
a+"px";d.height="0";d.border=d.border||"1px solid #aaa";d.background=d.background||"#fff";d.zIndex=_.ss(this);d.overflow="hidden";d.boxShadow=d.MozBoxShadow=d.webkitBoxShadow=d.boxShadow||"0 2px 2px rgba(0,0,0,0.3)";_.or(f,d);_.or(k,{left:"-1000px",top:"-1000px",position:"absolute",width:a+"px",height:b+"px"});this.w0=f.offsetWidth-a;this.y0=f.offsetHeight;d="auto"==c?["top","start"]:c.split("-");g=_.Ir(g);this.Us="bottom"==d[0];this.Vv="right"==d[1]||"left"!=d[1]&&g;this.Wg=DG(this,a,b,"auto"==c);
this.qD=_.q.setTimeout((0,_.J)(this.r_,this),500);this.ya.V(f,"mouseover",this.JB);this.ya.Oq(f,"mouseout",this.IB,!1,this);e&&_.q.setTimeout((0,_.J)(function(){this.vp||this.ya.V(document,"click",this.dX)},this),0)};
_.h.open=function(){this.create();this.ka.Jf(this.Aa);this.ka.Sd("resize",(0,_.J)(this.resize,this));this.ka.Mg("showMenu",(0,_.J)(this.cM,this));var a=this.ka.methods;a.setHideOnLeave=(0,_.J)(this.Br,this);a.displayStateCallback&&(this.pG=a.displayStateCallback,delete a.displayStateCallback);this.ka.kg(this.Am,{height:"100%"});_.EG(this,this.Wg)};
_.h.yd=function(a){this.vp||(a=a||{},this.Am.style.left="0",this.Am.style.top="0",this.nj&&(_.Zd(this.nj),this.nj=null),this.qD&&(_.q.clearTimeout(this.qD),this.qD=null),FG(this,parseInt(a.width,10)||parseInt(this.ka.width,10)||this.Wg.width,parseInt(a.height,10)||parseInt(this.ka.height,10)||this.Wg.height))};_.h.resize=function(a){this.vp||FG(this,isNaN(+a.width)?this.Wg.width:+a.width,isNaN(+a.height)?this.Wg.height:+a.height)};_.h.close=function(){this.CA?GG(this):(this.gy=!0,HG(this))};
_.h.$j=function(a,b){for(var c,d=1,e=arguments.length;d<e&&(c=this.ua[arguments[d]],void 0===c);++d);if(void 0!==c){if(c&&"object"==typeof c){d={};for(var f in c)d[f]=c[f];return d}return c}return a};
var DG=function(a,b,c,d){var e=a.yh(),f=_.Xr(e.offsetParent);f.right-=a.w0;f.bottom-=a.y0;if(d){var g=e.offsetLeft;d=g+b<f.right;g=g+e.offsetWidth-b>=f.left;a.Vv=a.Vv?!d||g:!d&&g;g=e.offsetTop;d=g+c<f.bottom;g=g+e.offsetHeight-c>=f.top;a.Us=a.Us?!d||g:!d&&g}d=a.lq(a.Vv,e.offsetLeft,e.offsetWidth,b,f.left,f.right);a=a.lq(a.Us,e.offsetTop,e.offsetHeight,c,f.top,f.bottom);return new AG(b,c,d,a,1)};
_.CG.prototype.lq=function(a,b,c,d,e,f){return a?(a=b+c,Math.min(f-a,Math.max(e+d-a,0))):Math.max(e-b,Math.min(f-b-d,0))};var FG=function(a,b,c){a.ka.Ma().style.width=b+"px";a.ka.Ma().style.height=c+"px";a.Am.style.width=b+"px";a.Am.style.height=c+"px";b=a.mQ?DG(a,b,c,!1):BG(a.xz,b,c);a.Wg=b;a.mk||IG(a,b)};_.h=_.CG.prototype;_.h.Br=function(a){this.zq=!!a};_.h.JB=function(){!this.mk&&this.Jl&&(_.q.clearTimeout(this.Jl),this.Jl=null)};
_.h.IB=function(a){if(!(this.mk||this.Jl||!this.zq||a.relatedTarget&&_.ce(this.Aa,a.relatedTarget))){var b=_.cs(this.Aa);a=a.clientY>b.top&&a.clientY<b.top+b.height?0:300;this.Jl=_.q.setTimeout((0,_.J)(this.Aq,this),a)}};_.h.dX=function(a){_.rs(this.Aa,a)||this.Aq()};_.h.cM=function(a){this.show(!!a||void 0===a)};_.h.show=function(a){a?this.tD():this.Aq()};_.h.tD=function(){!this.vp&&this.CA&&(this.mk=this.CA=!1,_.EG(this,this.Wg))};
_.EG=function(a,b){JG(a,BG(b,void 0,0,0));_.q.setTimeout((0,_.J)(function(){this.mk||(this.Wg=b,this.OD&&_.Zy(this.Aa,"width 350ms cubic-bezier(.23, .50, .32, 1),height 350ms cubic-bezier(.23, .50, .32, 1),left 350ms cubic-bezier(.23, .50, .32, 1),top 350ms cubic-bezier(.23, .50, .32, 1),opacity 350ms cubic-bezier(.23, .50, .32, 1)"),IG(this,b),this.Ys(!0,!1),this.Jr&&(_.q.clearTimeout(this.Jr),this.gy=!1),this.Jr=_.q.setTimeout((0,_.J)(this.Ys,this,!0,!0),350))},a),0)};
_.CG.prototype.Aq=function(){this.mk||HG(this)};
var HG=function(a){a.mk||(a.Ys(!1,!1),IG(a,BG(a.xz,void 0,0,0)),a.mk=!0,a.Jr&&_.q.clearTimeout(a.Jr),a.Jr=_.q.setTimeout((0,_.J)(function(){this.CA=!0;this.gy?(GG(this),this.gy=!1):(this.OD&&_.Zy(this.Aa,""),this.Aa.visibility="hidden",this.Aa.left="-1000px",this.Aa.top="-1000px");this.Ys(!1,!0)},a),350))},GG=function(a){a.vp=!0;_.Dp(a.ya);a.ya=null;a.Jl&&(_.q.clearTimeout(a.Jl),a.Jl=null);a.Om&&(_.q.clearTimeout(a.Om),a.Om=null);_.Zd(a.Aa);a.Aa=null;_.Zd(a.yh());a.Am=null;a.nj=null};
_.CG.prototype.Ys=function(a,b){var c=this.pG;c&&_.q.setTimeout(function(){c(a,b)},0)};_.CG.prototype.r_=function(){this.nj=document.createElement("div");this.nj.style.width=this.nj.style.height="100%";this.nj.style.position="absolute";this.nj.style.background="url(//ssl.gstatic.com/ui/v1/activityindicator/loading_gs.gif) no-repeat "+(this.Wg.width-19)/2+"px "+(this.Wg.height-19)/2+"px";this.Aa.appendChild(this.nj)};
var IG=function(a,b){if(!a.mk)if(a.OD)JG(a,b);else{var c=(0,_.Za)()-20+350;a.Om&&_.q.clearTimeout(a.Om);a.JJ(a.xz,b,c)}},JG=function(a,b){var c=a.Aa,d=a.yh();c.style.left=a.Vv?d.offsetLeft+d.offsetWidth+b.Cm-b.width+"px":d.offsetLeft+b.Cm+"px";c.style.width=b.width+"px";c.style.top=a.Us?d.offsetTop+d.offsetHeight+b.Dm-b.height+"px":d.offsetTop+b.Dm+"px";c.style.height=b.height+"px";_.Rr(c,b.opacity);a.xz=b};
_.CG.prototype.JJ=function(a,b,c){this.Om=null;if(!this.vp&&!a.equals(b)){var d=(0,_.Za)();d>=c?JG(this,b):(JG(this,a.interpolate(b,1-Math.pow(1-Math.min(1-(c-d)/350,1),3))),this.Om=_.q.setTimeout((0,_.J)(this.JJ,this,a,b,c),20))}};_.CG.prototype.open=_.CG.prototype.open;_.CG.prototype.onready=_.CG.prototype.yd;_.CG.prototype.close=_.CG.prototype.close;

_.ol["slide-menu"]=function(a){var b=new _.CG(_.$T(a)),c=new _.xs(b);b.open=function(){};b.create();a.attributes={height:"100%"};a.where=b.Am;a.onClose=function(){b.close()};a.onRestyle=function(d){if(d){var e=!1;d.hasOwnProperty("showMenu")&&(b.cM(d.showMenu),e=!0);d.hasOwnProperty("setHideOnLeave")&&(b.Br(d.setHideOnLeave),e=!0);e||b.resize(d)}};a.onCreate=function(d){d.Oc=function(){return this.du("openerIframe")};c.ka=b.ka=d;d.Jf(b.Aa);d.register("_ready",(0,_.J)(b.yd,b),_.Hl);b.pG=function(e,
f){!d.Mb&&d.bo([e,f])};_.EG(b,b.Wg);c.open()}};

});
// Google Inc.
