/* JS */ gapi.loaded_3(function(_){var window=this;
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Nr;Nr=function(a){return(a=a.exec(_.zb))?a[1]:""};_.Or=function(){if(_.Ug)return Nr(/Firefox\/([0-9.]+)/);if(_.uc||_.vc||_.sc)return _.Oc;if(_.Yg)return _.oc()?Nr(/CriOS\/([0-9.]+)/):Nr(/Chrome\/([0-9.]+)/);if(_.Zg&&!_.oc())return Nr(/Version\/([0-9.]+)/);if(_.Vg||_.Wg){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.zb);if(a)return a[1]+"."+a[2]}else if(_.Xg)return(a=Nr(/Android\s+([0-9.]+)/))?a:Nr(/Version\/([0-9.]+)/);return""}();

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.Pr=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};_.h=_.Pr.prototype;_.h.clone=function(){return new _.Pr(this.left,this.top,this.width,this.height)};_.h.SA=_.da(27);_.h.intersects=function(a){return this.left<=a.left+a.width&&a.left<=this.left+this.width&&this.top<=a.top+a.height&&a.top<=this.top+this.height};
_.h.contains=function(a){return a instanceof _.Cq?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};_.h.distance=function(a){var b=a.x<this.left?this.left-a.x:Math.max(a.x-(this.left+this.width),0);a=a.y<this.top?this.top-a.y:Math.max(a.y-(this.top+this.height),0);return Math.sqrt(b*b+a*a)};_.h.jn=function(){return new _.Dq(this.width,this.height)};
_.h.getCenter=function(){return new _.Cq(this.left+this.width/2,this.top+this.height/2)};_.h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};_.h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.h.translate=function(a,b){a instanceof _.Cq?(this.left+=a.x,this.top+=a.y):(this.left+=a,"number"===typeof b&&(this.top+=b));return this};_.h.scale=function(a,b){b="number"===typeof b?b:a;this.left*=a;this.width*=a;this.top*=b;this.height*=b;return this};_.Qr=function(a){return _.sr(a,"position")};
_.Rr=function(a,b){a=a.style;"opacity"in a?a.opacity=b:"MozOpacity"in a?a.MozOpacity=b:"filter"in a&&(a.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")};
_.Sr=function(){if(_.Bc){var a=/Windows NT ([0-9.]+)/;return(a=a.exec(_.zb))?a[1]:"0"}return _.Ac?(a=/10[_.][0-9_.]+/,(a=a.exec(_.zb))?a[0].replace(/_/g,"."):"10"):_.Dc?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(_.zb))?a[1]:""):_.Ec||_.Fc||_.Gc?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(_.zb))?a[1].replace(/_/g,"."):""):""}();

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Tr;Tr=function(a,b){return(b=_.rr(a,b))?_.Kr(a,b):0};_.Ur=function(a,b){if(_.uc){var c=Tr(a,b+"Left"),d=Tr(a,b+"Right"),e=Tr(a,b+"Top");a=Tr(a,b+"Bottom");return new _.mr(e,d,a,c)}c=_.qr(a,b+"Left");d=_.qr(a,b+"Right");e=_.qr(a,b+"Top");a=_.qr(a,b+"Bottom");return new _.mr(parseFloat(e),parseFloat(d),parseFloat(a),parseFloat(c))};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Vr,Wr,ds;_.Pr.prototype.SA=_.Vc(27,function(a){var b=Math.max(this.left,a.left),c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top);a=Math.min(this.top+this.height,a.top+a.height);d<=a&&(this.left=b,this.top=d,this.width=c-b,this.height=a-d)}});Vr=function(a,b){return new _.Cq(a.x-b.x,a.y-b.y)};
Wr=function(a){if(_.uc&&!_.Sc(8))return a.offsetParent;var b=_.Jd(a),c=_.sr(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(11==a.nodeType&&a.host&&(a=a.host),c=_.sr(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null};
_.Xr=function(a){for(var b=new _.mr(0,Infinity,Infinity,0),c=_.Kd(a),d=c.vb().body,e=c.vb().documentElement,f=_.Hq(c.tb);a=Wr(a);)if(!(_.uc&&0==a.clientWidth||_.yc&&0==a.clientHeight&&a==d)&&a!=d&&a!=e&&"visible"!=_.sr(a,"overflow")){var g=_.wr(a),k=new _.Cq(a.clientLeft,a.clientTop);g.x+=k.x;g.y+=k.y;b.top=Math.max(b.top,g.y);b.right=Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);
b.top=Math.max(b.top,f);c=_.Gq(c.Ab());b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null};_.cs=function(a){var b=_.wr(a);a=_.Er(a);return new _.Pr(b.x,b.y,a.width,a.height)};ds=function(a,b){return(b&8&&_.Ir(a)?b^4:b)&-9};
_.es=function(a,b,c,d,e,f,g,k,l){var m;if(m=c.offsetParent){var n="HTML"==m.tagName||"BODY"==m.tagName;if(!n||"static"!=_.Qr(m)){var p=_.wr(m);if(!n){n=_.Ir(m);var t;if(t=n){t=_.Zg&&0<=_.yb(_.Or,10);var r=_.Hc&&0<=_.yb(_.Sr,10);t=_.xc||t||r}n=t?-m.scrollLeft:!n||_.wc&&_.Qc("8")||"visible"==_.sr(m,"overflowX")?m.scrollLeft:m.scrollWidth-m.clientWidth-m.scrollLeft;p=Vr(p,new _.Cq(n,m.scrollTop))}}}m=p||new _.Cq;p=_.cs(a);(n=_.Xr(a))&&p.SA(new _.Pr(n.left,n.top,n.right-n.left,n.bottom-n.top));n=_.Kd(a);
r=_.Kd(c);n.vb()!=r.vb()&&(t=n.vb().body,r=_.Br(t,r.Ab()),r=Vr(r,_.wr(t)),!_.uc||_.Sc(9)||_.Eq(n.tb)||(r=Vr(r,_.Iq(n.tb))),p.left+=r.x,p.top+=r.y);a=ds(a,b);b=p.left;a&4?b+=p.width:a&2&&(b+=p.width/2);b=new _.Cq(b,p.top+(a&1?p.height:0));b=Vr(b,m);e&&(b.x+=(a&4?-1:1)*e.x,b.y+=(a&1?-1:1)*e.y);if(g)if(l)var v=l;else if(v=_.Xr(c))v.top-=m.y,v.right-=m.x,v.bottom-=m.y,v.left-=m.x;e=v;l=b.clone();v=ds(c,d);d=_.Er(c);a=k?k.clone():d.clone();k=l;l=a;k=k.clone();l=l.clone();a=0;if(f||0!=v)v&4?k.x-=l.width+
(f?f.right:0):v&2?k.x-=l.width/2:f&&(k.x+=f.left),v&1?k.y-=l.height+(f?f.bottom:0):f&&(k.y+=f.top);g&&(e?(f=k,v=l,a=0,65==(g&65)&&(f.x<e.left||f.x>=e.right)&&(g&=-2),132==(g&132)&&(f.y<e.top||f.y>=e.bottom)&&(g&=-5),f.x<e.left&&g&1&&(f.x=e.left,a|=1),g&16&&(b=f.x,f.x<e.left&&(f.x=e.left,a|=4),f.x+v.width>e.right&&(v.width=Math.min(e.right-f.x,b+v.width-e.left),v.width=Math.max(v.width,0),a|=4)),f.x+v.width>e.right&&g&1&&(f.x=Math.max(e.right-v.width,e.left),a|=1),g&2&&(a|=(f.x<e.left?16:0)|(f.x+v.width>
e.right?32:0)),f.y<e.top&&g&4&&(f.y=e.top,a|=2),g&32&&(b=f.y,f.y<e.top&&(f.y=e.top,a|=8),f.y+v.height>e.bottom&&(v.height=Math.min(e.bottom-f.y,b+v.height-e.top),v.height=Math.max(v.height,0),a|=8)),f.y+v.height>e.bottom&&g&4&&(f.y=Math.max(e.bottom-v.height,e.top),a|=2),g&8&&(a|=(f.y<e.top?64:0)|(f.y+v.height>e.bottom?128:0)),g=a):g=256,a=g);f=new _.Pr(0,0,0,0);f.left=k.x;f.top=k.y;f.width=l.width;f.height=l.height;g=a;g&496||(_.ur(c,new _.Cq(f.left,f.top)),a=f.jn(),d==a||d&&a&&d.width==a.width&&
d.height==a.height||(f=a,d=_.Eq(_.Kd(_.Jd(c)).tb),!_.uc||_.Qc("10")||d&&_.Qc("8")?(c=c.style,_.xc?c.MozBoxSizing="border-box":_.yc?c.WebkitBoxSizing="border-box":c.boxSizing="border-box",c.width=Math.max(f.width,0)+"px",c.height=Math.max(f.height,0)+"px"):(k=c.style,d?(d=_.Ur(c,"padding"),c=_.xr(c),k.pixelWidth=f.width-c.left-d.left-d.right-c.right,k.pixelHeight=f.height-c.top-d.top-d.bottom-c.bottom):(k.pixelWidth=f.width,k.pixelHeight=f.height))));return g};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var js;js=function(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null};_.ks=function(a){if(1==a.nodeType)return _.Ar(a);a=a.changedTouches?a.changedTouches[0]:a;return new _.Cq(a.clientX,a.clientY)};
if("undefined"===typeof ls)var ls={};_.ms=function(a){this.ka=a;this.ua=a.kc()};_.ms.prototype.Vq=function(){ns(this)};
var ns=function(a){var b=a.ka.Oc();if(a.ua.anchorBox&&b&&b.Ma())b=_.wr(b.Ma()),a.ua.anchorBox.left+=b.x,a.ua.anchorBox.top+=b.y;else{b=a.ua.anchor;if("_default"!=b&&"_iframe"!=b){var c=_.Ld(document,b);if(c)a.ua.anchorBox=_.cs(c);else{_.ab("Anchor not found in DOM: "+b+'. Falling back to "_default".');a.ua.anchor="_default";return}}"_iframe"==b&&(b=_.Gq(),a.ua.anchorBox=new _.Pr(0,0,b.width,b.height))}a.ua.anchor=""};_.ms.prototype.onBeforeParentOpen=_.ms.prototype.Vq;
_.os=function(a){_.ms.call(this,a)};_.fj(_.os,_.ms);_.h=_.os.prototype;_.h.open=function(){var a=this.ua,b=document.createElement("ins");document.getElementById(a.container).appendChild(b);b.style.display="block";_.or(b,a.containerCss);this.ka.Jf(b);this.ka.kg(b)};_.h.yd=function(){document.getElementById(this.ka.id).style.height=this.ka.height+"px"};_.h.close=function(){_.Zd(this.ka.Bb());_.Zd(this.xg);this.xg=null};_.h.cw=_.da(12);
_.h.yh=function(){if(this.xg)return this.xg;var a=this.ua;!a.anchorBox&&a.anchor&&ns(this);var b=this.ka.Oc();if("_default"==a.anchor&&b){var c=_.cs(_.Ld(document,b.Bb()));a.anchorBox=c}if(!a.anchorBox)return _.ab("No anchor box defined."),null;a=new _.Cq(a.anchorBox.left,a.anchorBox.top);b&&(b=_.Br(b.Ma(),window),this.Wl=new _.Cq,this.Wl.x=b.x,this.Wl.y=b.y,a.x+=b.x,a.y+=b.y,_.ps(a));this.Ex=a;b=_.qs(this,!0);this.xg=document.createElement("ins");this.xg.style.cssText=b;document.body.appendChild(this.xg);
return this.xg};_.qs=function(a,b){var c=a.ua;return"position: absolute !important;background-color: transparent !important;left: "+a.Ex.x+"px !important;top: "+a.Ex.y+"px !important;width: "+c.anchorBox.width+"px !important;height: "+c.anchorBox.height+"px !important;z-index: -10000 !important;display: "+(b?"block":"none")+" !important;"};
_.rs=function(a,b){var c=0,d=0;if(b.pageX||b.pageY)c=b.pageX,d=b.pageY;else if(b.clientX||b.clientY)c=b.target?b.target:b.srcElement,d=c.ownerDocument&&c.ownerDocument.parentWindow?c.ownerDocument.parentWindow:window,_.uc?(c=d.document.documentElement.scrollLeft,d=d.document.documentElement.scrollTop):(c=d.pageXOffset,d=d.pageYOffset),c=b.clientX+c,d=b.clientY+d;b=new _.Cq(c,d);a=_.cs(a);return a=new _.mr(a.top,a.left+a.width,a.top+a.height,a.left),a.contains(b)};
_.ps=function(a){var b=window,c=document.body,d=_.wr(c);b=c.currentStyle||b.getComputedStyle(c,"");b.position&&"static"!=b.position&&(a.x-=d.x,a.y-=d.y)};_.ss=function(a){var b=a.ka.Oc()&&a.ka.Oc().Bb();b=b&&b.style.zIndex?parseInt(b.style.zIndex,10)+1:0;return Math.min(2147483647,Math.max(2E9,a.ua.zIndex||b))};
var ts,us,vs;ts={"bottom-center":1,"bottom-end":13,"bottom-left":1,"bottom-right":5,"bottom-start":9,"left-bottom":1,"left-center":0,"left-top":0,"right-bottom":5,"right-center":4,"right-top":4,"top-center":0,"top-end":12,"top-left":0,"top-right":4,"top-start":8};us={"bottom-center":!0,"top-center":!0};vs={"left-center":!0,"right-center":!0};
_.ws=function(a,b,c,d,e){e=e||{x:0,y:0};if(us[b]){var f=_.Er(a).width/2;e.x="top-right"==d||"bottom-right"==d?e.x+f:e.x-f}us[d]&&(f=_.Er(c).width/2,e.x+=f);vs[b]&&(f=_.Er(a).height/2,e.y="right-bottom"==d||"left-bottom"==d?e.y+f:e.y-f);vs[d]&&(e.y+=_.Er(c).height/2);_.es(c,ts[d],a,ts[b],new _.Cq(e.x,e.y));d=js(a,function(g){if(g==document)return!1;g=_.Qr(g);return!!g&&"static"!=g});c=b=0;d&&(c=_.wr(d),b=-c.x,c=-c.y);a=a.style;parseInt(a.left,10)<b&&(a.left=b+"px");parseInt(a.top,10)<c&&(a.top=c+"px")};
_.xs=function(a){_.ms.call(this,a.ka);this.mg=a;this.Yx=[]};_.fj(_.xs,_.os);_.h=_.xs.prototype;_.h.Vq=function(){this.mg.Vq()};_.h.open=function(){this.mg.open();(this.ua.closeClickDetection||this.ua.hideClickDetection)&&ys(this)};_.h.yd=function(a){this.mg.yd(a)};_.h.$J=function(a){this.mg.onRenderStart&&this.mg.onRenderStart(a)};_.h.close=function(){if(this.ua.closeClickDetection||this.ua.hideClickDetection)_.qb(this.Yx,function(a){_.eq(a)}),this.Yx=[];this.mg.close()};
var ys=function(a){_.qb(["click","touchstart"],(0,_.J)(function(b){this.Yx.push(_.Yp(document,b,(0,_.J)(this.LQ,this),!0))},a))};_.xs.prototype.LQ=function(a){_.rs(this.ka.Bb(),a)||(this.ua.hideClickDetection&&this.mg.show?this.mg.show(!1):this.close())};_.xs.prototype.onBeforeParentOpen=_.xs.prototype.Vq;_.xs.prototype.open=_.xs.prototype.open;_.xs.prototype.onready=_.xs.prototype.yd;_.xs.prototype.onRenderStart=_.xs.prototype.$J;_.xs.prototype.close=_.xs.prototype.close;

_.rG=function(a){_.ms.call(this,a.ka);this.mg=a;this.Ap=null};_.fj(_.rG,_.os);_.rG.prototype.open=function(){this.ua.targetPos=this.ua.targetPos||"top-start";this.ua.anchorPos=this.ua.anchorPos||"bottom-start";var a=this.yh(),b=this.ka.Bb();b?(b.style.visibility="hidden",b.style.position="absolute",a.parentNode.appendChild(b)):this.mg.open()};
_.rG.prototype.yd=function(){if(this.ua.closeClickDetection){var a=this,b=function(e){_.rs(a.ka.Bb(),e)||(a.ka.close(),a.Ap=null)};document.vQ?(document.vQ("click",b),this.Ap=function(){document.removeEventListener("click",b,!1)}):document.attachEvent&&(document.attachEvent("onclick",b),this.Ap=function(){document.detachEvent("onclick",b)})}var c=document.getElementById(this.ka.id),d=this.ka.Bb();c.style.height=this.ka.height+"px";(c=this.yh())&&_.ws(d,this.ua.targetPos,c,this.ua.anchorPos,{x:this.ua.leftOffset||
0,y:this.ua.topOffset||0});d.style.visibility="visible"};_.rG.prototype.close=function(){this.mg.close();this.Ap&&this.Ap()};_.rG.prototype.open=_.rG.prototype.open;_.rG.prototype.onready=_.rG.prototype.yd;_.rG.prototype.close=_.rG.prototype.close;
_.sG=function(a){_.ms.call(this,a)};_.fj(_.sG,_.os);_.h=_.sG.prototype;_.h.create=function(a){this.Ka=document.createElement("div");var b={position:"absolute",top:"-10000px",zIndex:_.ss(this)};this.ua.width&&(b.width=this.ua.width+"px");for(var c in b)this.Ka.style[c]=b[c];(a||document.body).appendChild(this.Ka)};_.h.open=function(a){this.ka.Mg("updateContainer",(0,_.J)(this.vj,this));this.create(a);this.ka.kg(this.Ka);this.ka.Jf(this.Ka)};
_.h.yd=function(){var a=tG(this);if(a){var b=document.getElementById(this.ka.ma());b.style.height=a.height+"px";b.style.width=a.width+"px";this.ka.width=a.width;this.ka.height=a.height;b.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)"}};_.h.close=function(){this.Ka.parentNode&&this.Ka.parentNode.removeChild(this.Ka)};
_.h.vj=function(a,b,c){var d=this.ka.Bb();d&&(a?(this.Yg(b,c),d.style.opacity=0,d.style.display="",window.setTimeout((0,_.J)(function(){uG(d,!0);d.style.opacity=1},this),0)):(d.style.display="none",uG(d,!1),d.style.opacity=0))};var uG=function(a,b){for(var c=0;c<vG.length;c++)a.style[vG[c]]=b?"opacity .13s linear":""};
_.sG.prototype.Yg=function(a,b){var c=this.ka.Oc();a+=10;b+=10;if(_.Ta.util&&(c&&(c=_.Br(c.Bb(),window),a+=c.x,b+=c.y),c=tG(this))){var d=_.Gq(window),e=_.Iq(document);if(d.width&&(a=Math.min(a,d.width+e.x-c.width-8),b+c.height>d.height+e.y-8)){b-=20+c.height;var f=window,g=f.document;d=0;if(g){d=g.body;var k=g.documentElement;if(k&&d)if(f=_.Fq(f).height,_.Eq(g)&&k.scrollHeight)d=k.scrollHeight!=f?k.scrollHeight:k.offsetHeight;else{g=k.scrollHeight;var l=k.offsetHeight;k.clientHeight!=l&&(g=d.scrollHeight,
l=d.offsetHeight);d=g>f?g>l?g:l:g<l?g:l}else d=0}b=Math.max(b,Math.min(e.y+1,d-c.height))}}c=this.ka.Bb();c.style.left=a+"px";c.style.top=b+"px"};var tG=function(a){return a.ka.width&&a.ka.height?{width:a.ka.width,height:a.ka.height}:(a=a.ka.Ma())&&a.offsetWidth&&a.offsetHeight?{width:a.offsetWidth,height:a.offsetHeight}:null},vG=["transition","WebkitTransition","MozTransition","OTranstion","msTransition"];_.sG.prototype.open=_.sG.prototype.open;_.sG.prototype.onready=_.sG.prototype.yd;
_.sG.prototype.close=_.sG.prototype.close;
_.wG=function(a){_.ms.call(this,a)};_.fj(_.wG,_.os);_.wG.prototype.open=function(){var a=document.createElement("div");_.or(a,{top:"-10000px",position:"absolute",zIndex:_.ss(this)});this.yh().parentNode.appendChild(a);this.ka.Jf(a);this.ka.kg(a)};
_.wG.prototype.yd=function(){var a=document.getElementById(this.ka.id);a.style.height=this.ka.height+"px";a.style.width=this.ka.width+"px";a.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)";var b=this.ka.Bb();b.style.lineHeight=0;var c=this.yh(),d=this.ua.targetPos||"top-start",e=this.ua.anchorPos||"bottom-start",f=this.ua.leftOffset||0,g=this.ua.topOffset||0;_.ws(b,d,c,e,{x:f,y:g});var k=_.Gq(window),l=_.Iq(document),m=b.offsetLeft<l.x||b.offsetLeft+b.offsetWidth>k.width+l.x;k=b.offsetTop<l.y||b.offsetTop+
b.offsetHeight>k.height+l.y;d=xG(d,m,k);e=xG(e,m,k);_.ws(b,d,c,e,{x:f*(m?-1:1),y:g*(k?-1:1)});b.style.visibility="visible";this.jv=_.Yp(document,"mouseover",(0,_.J)(function(n){n.target===a&&this.$k&&(window.clearTimeout(this.$k),this.$k=null)},this));this.CB=_.Yp(document,"mouseout",(0,_.J)(function(n){n.target===a&&(this.$k=window.setTimeout((0,_.J)(this.ka.close,this.ka),1E3))},this))};
var xG=function(a,b,c){a=a.split("-");for(var d=0;2>d;d++)b&&yG[a[d]]&&(a[d]=yG[a[d]]),c&&zG[a[d]]&&(a[d]=zG[a[d]]);return a.join("-")};_.wG.prototype.close=function(){this.jv&&(_.eq(this.jv),_.eq(this.CB),this.CB=this.jv=null);this.$k&&(window.clearTimeout(this.$k),this.$k=null);_.os.prototype.close.call(this)};_.wG.prototype.jv=null;_.wG.prototype.CB=null;_.wG.prototype.$k=null;var yG={end:"start",left:"right",right:"left",start:"end"},zG={top:"bottom",bottom:"top"};_.wG.prototype.open=_.wG.prototype.open;
_.wG.prototype.onready=_.wG.prototype.yd;_.wG.prototype.close=_.wG.prototype.close;

var aU,bU,cU;for(_.$T=function(a){return{kc:function(){return a},Oc:function(){return a.openerIframe}}},aU=function(a){(new _.ms(_.$T(a))).Vq()},bU="bubble circlepicker float hover hover-menu slide-menu".split(" "),cU=0;cU<bU.length;cU++)_.pl[bU[cU]]=aU;

_.ol.hover=function(a){var b=new _.sG(_.$T(a));b.create(a.where);a.where=b.Ka;a.onClose=function(){b.close()};a.onRestyle=function(c){if(c.updateContainer){var d=c.updateContainer;b.vj(d.visible,d.x,d.y)}c.width&&(b.ka.width=c.width);c.height&&(b.ka.height=c.height)};a.onCreate=function(c){b.ka=c;c.Oc=function(){return a.openerIframe};c.register("_ready",(0,_.J)(b.yd,b),_.Hl);c.updateContainer=function(d,e,f){b.vj(d,e,f)}}};

var rP=function(a,b){this.Uc=a;this.Re=b};rP.prototype.uv=function(a){this.Uc.or(this.Re,a)};rP.prototype.Xq=function(){this.Uc.oh(this.Re)};rP.prototype.rv=function(){this.Uc.oc(this.Re)};rP.prototype.iaa=function(a,b,c,d,e){this.Uc.oe(this.Re,a,b,c,d,e)};
_.sP=function(a){this.w=this.Db=a;this.n=null;this.slf=0;this.ssh=!1;this.sen=!0;this.shl=this.itm=null};_.sP.prototype.sm=function(a,b){this.Db.oo(new rP(a,this));this.n=b};_.sP.prototype.sh=function(){this.Db.show()};_.sP.prototype.hi=function(){this.Db.mc()};_.sP.prototype.cl=function(){this.Db.close()};_.sP.prototype.en=function(){this.Db.enable()};_.sP.prototype.di=function(){this.Db.disable()};_.sP.prototype.hl=function(a){this.Db.NS(a)};_.sP.prototype.vr=function(a,b){this.Db.GT(a,b)};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.oU=function(a){return String(a).replace(/([A-Z])/g,"-$1").toLowerCase()};_.pU=!_.uc&&!_.Sg();

var cW=function(a){a.Uc.os(a.Re)},dW=function(a){this.Re=a;this.Ge=0;this.Lr=!1;this.AG=!0;this.Kk=null},eW=function(a){return 5==a.Ge||4==a.Ge};dW.prototype.isEnabled=function(){return this.AG};dW.prototype.Ic=function(a){this.AG=a};
var fW=function(a,b,c){this.Nv=a||{};this.OA=b||0;this.HV=c||0;a={};b=(0,_.J)(this.jH,this);a.fc=b;b=(0,_.J)(this.iC,this);a.rc=b;b=(0,_.J)(this.oD,this);a.sc=b;b=(0,_.J)(this.yq,this);a.hc=b;b=(0,_.J)(this.qp,this);a.cc=b;b=(0,_.J)(this.bI,this);a.os=b;b=(0,_.J)(this.aI,this);a.or=b;b=(0,_.J)(this.ZH,this);a.oh=b;b=(0,_.J)(this.XH,this);a.oc=b;b=(0,_.J)(this.YH,this);a.oe=b;b=(0,_.J)(this.$H,this);a.oi=b;this.Uc=a};_.h=fW.prototype;
_.h.iC=function(a,b,c){try{a+=null!=b?"_"+b:"",c.sm(this.Uc,a),this.Nv[a]=new dW(c)}catch(d){return!1}return!0};_.h.jH=function(a,b){return(a=this.Nv[a+(null!=b?"_"+b:"")])?a.Re:null};_.h.oD=function(a){var b=gW(this,a);if(b&&(2==b.Ge||3==b.Ge)&&b.isEnabled()&&!b.Lr){try{a.sh()}catch(c){}b.Lr=!0}};_.h.yq=function(a){var b=gW(this,a);if(b&&(2==b.Ge||3==b.Ge||eW(b))&&b.Lr){try{a.hi()}catch(c){}b.Lr=!1}};_.h.qp=function(a){var b=gW(this,a);if(b&&5!=b.Ge){try{this.yq(a),a.cl()}catch(c){}hW(this,b)}};
_.h.bI=function(a){(a=gW(this,a))&&0==a.Ge&&(iW(this,a),a.Ge=1)};var iW=function(a,b){a.OA?(a=setTimeout((0,_.J)(function(){eW(b)||jW(this,b)},a),a.OA),b.Kk=a):jW(a,b)},jW=function(a,b){var c=a.HV-a.OA;0<c&&(a=setTimeout((0,_.J)(function(){eW(b)||(b.Ge=4,this.qp(b.Re))},a),c),b.Kk=a)},kW=function(a){null!=a.Kk&&(clearTimeout(a.Kk),a.Kk=null)};_.h=fW.prototype;_.h.aI=function(a){(a=gW(this,a))&&!eW(a)&&1==a.Ge&&(kW(a),a.Ge=3)};_.h.ZH=function(a){(a=gW(this,a))&&!eW(a)&&(a.Lr=!1)};
_.h.XH=function(a){var b=gW(this,a);if(b&&!eW(b)){try{this.yq(a)}catch(c){}hW(this,b)}};_.h.YH=function(a){(a=gW(this,a))&&!eW(a)&&(a.Ge=4,this.qp(a.Re))};_.h.$H=function(a,b){(a=gW(this,a))&&!eW(a)&&2<=b&&4>=b&&!eW(a)&&(kW(a),a.Ge=2)};var hW=function(a,b){kW(b);b.Ge=5;a=a.Nv;for(var c in a)a[c]==b&&delete a[c]},gW=function(a,b){return a.Nv[b.n]},lW=function(){this.Uc=window.gbar.wg};_.h=lW.prototype;_.h.iC=function(a,b,c){return this.Uc.rc(a,b,c)};_.h.jH=function(a,b){return this.Uc.fc(a,b)};
_.h.oD=function(a){this.Uc.sc(a)};_.h.yq=function(a){this.Uc.hc(a)};_.h.qp=function(a){this.Uc.cc(a)};_.h.bI=function(a){this.Uc.os(a)};_.h.aI=function(a,b){this.Uc.or(a,b)};_.h.ZH=function(a){this.Uc.oh(a)};_.h.XH=function(a){this.Uc.oc(a)};_.h.YH=function(a,b,c,d,e,f){this.Uc.oe(a,b,c,d,e,f)};_.h.$H=function(a,b,c,d){this.Uc.oi(a,b,c,d)};var mW=function(){fW.call(this)};_.B(mW,fW);
var nW=function(a){if(window.___jsl.man)a(window.___jsl.man);else{var b=function(){var d=new mW;window.___jsl.man=d;a(d)};if(window.gbar){var c=function(){if(window.gbar.wg){var d=new lW;window.___jsl.man=d;a(d)}else b()};window.gbar.wg?c():window.gbar.qm?window.gbar.qm(c):b()}else b()}},oW=function(){return window.___jsl.man};
var pW=function(a){this.oZ=a;a.then((0,_.J)(function(){},this))},qW=function(a,b){a.oZ.then(function(c){var d=c.startFeedback;if(!d)throw Error("db`startFeedback");return d.apply(c,b)})},sW=function(a,b,c){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];e=rW(a,b).then(function(f){return f.apply(null,d)});return new pW(e)},tW={},rW=function(a,b){var c=tW[b];if(c)return c;c=(c=_.zp(b))?_.Pj(c):(new _.Lj(function(d,e){var f=(new _.Hd(document)).createElement("SCRIPT");
f.async=!0;_.sj(f,_.pd(a));f.onload=f.onreadystatechange=function(){f.readyState&&"loaded"!=f.readyState&&"complete"!=f.readyState||d()};f.onerror=e;(document.head||document.getElementsByTagName("head")[0]).appendChild(f)})).then(function(){var d=_.zp(b);if(!d)throw Error("eb`"+b+"`"+a);return d});return tW[b]=c};
var uW=function(a){this.xW=a};uW.prototype.t_=function(a){qW(this.xW,arguments)};var vW=_.Tb("https://www.gstatic.com/feedback/js/help/prod/service/lazy.min.js");rW(vW,"help.service.Lazy.create");
var wW={contactid:!0,cdu:!0,cmp:!0,email:!0,hl:!0,n:!0,m:!0,p:!0,src:!0,userid:!0,sp:!0,ytid:!0};_.Gb({nm:!0,s:!0,pr:!0,v:!0},wW);
var xW=function(){this.Dq=_.Vj();this.Dq.promise.then(function(a){_.or(a.Ma(),{border:"none","margin-bottom":"-4px"});_.or(a.Bb(),{"border-radius":"4px",overflow:"hidden","box-shadow":"rgba(0, 0, 0, 0.3) 0px 4px 16px"})})};_.h=xW.prototype;_.h.KA=function(a){_.$k.open(a,this.Dq.resolve)};_.h.BI=function(){this.Dq.promise.then(function(a){return a.close()})};_.h.JA=function(a,b,c,d){this.Dq.promise.then(function(e){return e.send(a,c,d,b)})};
_.h.IA=function(a,b,c){this.Dq.promise.then(function(d){return d.Uv({updateContainer:{visible:a,x:b,y:c}})})};_.h.Aj=function(a,b,c){_.$k.Aj(a,c,b)};
var yW=/(?:^|\s)g-(?:hovercard|profile)(?:$|\s)/,zW={loadDelay:400,hoverDelay:500,closeDelay:500},AW=0,BW=function(a){return document.body==a?"body":a.__cardid||null},CW=function(a){var b=BW(a);b||(b=a.__cardid=AW++);return String(b)},DW=function(a){var b=a.className||"getAttribute"in a&&a.getAttribute("class");!(b=b&&yW.test(b))&&(b=a.getAttribute)&&(b=/-[a-z]/.test("hovercardId")?!1:_.pU&&a.dataset?"hovercardId"in a.dataset:a.hasAttribute?a.hasAttribute("data-"+_.oU("hovercardId")):!!a.getAttribute("data-"+
_.oU("hovercardId")));return b||"getAttribute"in a&&a.getAttribute("oid")&&36==_.P("card/p")?!0:"G:HOVERCARD"==a.tagName.toUpperCase()},EW=function(a,b){var c={};_.Gb(c,zW,_.P("iframes/card")||{},_.P("card")||{});for(var d=[],e=a;e;e=e.parentNode){var f=BW(e);f&&b[f]&&d.push(b[f])}_.qb(d.reverse(),function(g){_.Gb(c,g)});b="G:HOVERCARD"==a.tagName.toUpperCase()?"":"data-";d=a.attributes;for(e=0;e<d.length;e++)_.bd(d[e].name,b)&&(c[d[e].name.substring(b.length)]=d[e].value);"getAttribute"in a&&a.getAttribute("oid")&&
36==_.P("card/p")&&(c.ytid=a.getAttribute("oid"));!c.userid&&"A"==a.tagName.toUpperCase()&&a.pathname&&(b=a.pathname.match(/^\/?(\d+)$/),/\.google\.com$/.test(a.hostname)&&b&&(c.userid=b[1]));c.hl||(c.hl=_.P("lang")||_.Je.getUrlParameters().hl||void 0);c.m=c.entity;c.src=c.source;delete c.entity;delete c.source;return c},FW=function(a,b){b=b[a];"number"!==typeof b&&(b=zW[a]);return 0>b?0:b};
var GW=function(a){this.lp=a;this.Re=new _.sP(this);this.Ga=null;this.Nu=!1;this.jJ=0;this.ip=!1};_.h=GW.prototype;
_.h.load=function(a){cW(this.Ci);a=_.wx(a,function(f,g){return wW[g]&&null!=f});a.origin=window.location.protocol+"//"+window.location.host;var b=this,c=this.lp,d={_event:function(f){if(!(f.timestamp<c.cB)){if("sgcp_ams"==f.event)c.Ju=!0,c.kv=!1;else if(c.Ju&&"mouseover"==f.event)c.kv=!0;else if(c.Ju&&"mouseout"==f.event)c.kv=!1;else if("sgcp_amh"==f.event)c.Ju=!1,c.kv||HW(c);else{var g=!1;switch(f.event){case "calendar":g=c.fh.scheduleEventHandler;break;case "chat":g=c.fh.sendChatHandler;break;case "email":g=
c.fh.sendEmailHandler;break;case "feedback":g=c.fh.feedbackHandler;break;case "videoChat":g=c.fh.videoChatHandler}g&&g(c.fh["hovercard-id"]||c.fh.userid||c.fh.email)}if("mouseover"==f.event||"sgcp_ams"==f.event)window.clearTimeout(c.Gh),c.Gh=null;if(f.cpid){for(g=document.getElementById(f.cpid);g&&"BODY"!=g.parentNode.tagName;)g=g.parentNode;c.dB=g}f.fromCard&&"mouseout"==f.event&&HW(c)}},_ready:(0,_.J)(this.yd,this),version:function(f){c.Qe(c.kj,{type:"circles_changed",version:f.v})},loaded:function(f){f.ri==
b.jJ&&b.rW()},rendered:function(){var f=b.lp.Sl,g=_.Iq(document);b.ip&&(b.vj(!0,f.x+g.x,f.y+g.y),b.ip=!1,f=b.lp,f.Qe(f.kj,{type:"show",frame:b.Ga}))},renderfailed:function(){b.ip=!1;b.vj(!1,0,0)},disposed:function(){b.Ga.close()},cardAction:function(f){IW(c,f)}},e=":card";!_.P("iframes/card/url")&&_.P("iframes/hovercard/url")&&(e=":hovercard");a=_.ei(_.hi(_.gi(new _.ci({disableMultiLevelParentRelay:!0,hover:!0}),d),_.Hl),a).Nd("hover").setUrl(e);_.P("card/relayOpenTop")&&(_.fi(a,-1),_.ii(a).JC("_default"));
_.$k.open(a.value(),(0,_.J)(function(f){this.Ga=f;_.or(f.Ma(),{border:"none","margin-bottom":"-4px"});_.or(f.Bb(),{"border-radius":"4px",overflow:"hidden","box-shadow":"rgba(0, 0, 0, 0.3) 0px 4px 16px"})},this))};_.h.yd=function(){this.Nu=!0;this.vj(!1,0,0);this.Ci.uv({});var a=this.lp;a.Rd&&a.jB(a.Rd)};_.h.oo=function(a){this.Ci=a};_.h.NS=function(a){this.Ga.send("getHealthc",void 0,a,_.Hl)};_.h.GT=function(a,b){this.Ga.send("getVarc",a,b,_.Hl)};
_.h.vj=function(a,b,c){this.Ga.updateContainer?this.Ga.updateContainer(a,b,c):this.Ga.Uv({updateContainer:{visible:a,x:b,y:c}})};_.h.show=function(){this.vj(!0,0,-1E4);this.Ga.send("render",void 0,void 0,_.Hl);this.ip=!0};_.h.mc=function(){this.Ga.send("hide",void 0,void 0,_.Hl);this.vj(!1,0,0);var a=this.lp;a.Qe(a.kj,{type:"hide"});a.kj=null;a.fh=null;this.ip=!1};_.h.close=function(){this.Ga.send("dispose",void 0,void 0,_.Hl)};_.h.enable=function(){};_.h.disable=function(){};
var JW=function(){this.OJ=0;this.iA=[];this.yi={};this.gt={};this.Xb={};this.cB=this.Gh=this.ig=this.yn=this.fh=this.kj=this.uc=this.Rd=this.sf=null;this.Sl={x:0,y:0};this.kv=this.Ju=!1;this.dB=null;this.OF=new Map;_.zp("gapi.load")("gapi.iframes.style.slide-menu")},KW=function(a,b,c,d){var e=CW(b);e=a.Xb[e]||(a.Xb[e]={});e[c]||(e[c]=d=(0,_.J)(d,a),b.addEventListener?b.addEventListener(c,d,"focus"==c||"blur"==c):("focus"==c?c="focusin":"blur"==c&&(c="focusout"),b.attachEvent("on"+c,d)))},LW=function(a,
b,c){(a=a.Xb[CW(b)])&&a[c]&&(b.addEventListener?b.removeEventListener(c,a[c],"focus"==c||"blur"==c):b.detachEvent("focus"==c?"onfocusin":"blur"==c?"onfocusout":"on"+c,a[c]),delete a[c])},MW=function(a,b){var c=a.Xb[b.id];if(c)for(var d in c)c.hasOwnProperty(d)&&LW(a,b,d)};_.h=JW.prototype;
_.h.hs=function(a,b,c){if(a=a||document.body){this.OJ++;var d=CW(a);b&&(this.yi[d]=b);c&&(this.gt[d]=c);KW(this,a,"mouseover",this.WH);KW(this,a,"mouseout",this.tA);KW(this,a,"mousedown",this.qu);KW(this,a,"focus",this.WH);KW(this,a,"blur",this.tA);KW(this,document.body,"mouseout",this.tA);KW(this,document.body,"mousedown",this.qu);c&&c.preload&&(b=this.Rd=document.createElement("div"),this.uc=EW(b,this.gt),NW(this))}else window.setTimeout((0,_.J)(this.hs,this),100)};
_.h.LD=function(a){if(a=a||document.body)if(HW(this,0),a!=document.body?MW(this,a):LW(this,document.body,"mouseover"),a=CW(a),delete this.yi[a],delete this.gt[a],!(0<--this.OJ)){MW(this,document.body);var b=this.sf;this.DA();this.sf=null;window.setTimeout(function(){var c=oW();c&&b&&c.qp(b.Re)},100)}};_.h.Sd=function(a){this.iA.push(a)};_.h.dm=function(a){_.yp(this.iA,a)};_.h.Qe=function(a,b){for(var c=[];a;){var d=BW(a);d&&this.yi[d]&&c.push(this.yi[d]);a=a.parentNode}_.Ee(c,this.iA);_.qb(c,function(e){e(b)})};
_.h.WH=function(a){this.cB=(0,_.Za)();var b=a.target||a.srcElement;if(b&&"IFRAME"!=b.tagName){for(;b&&!DW(b);)if(b=b.parentNode,!b||1!=b.nodeType)return;if(b)if(this.kj==b||this.Rd==b)this.Gh&&(window.clearTimeout(this.Gh),this.Gh=null);else{this.Rd=b;KW(this,b,"mousemove",this.xU);"focus"==a.type||"focusin"==a.type?(a=_.ks(b),this.Sl.x=a.x,this.Sl.y=a.y+b.offsetHeight):(this.Sl.x=a.clientX,this.Sl.y=a.clientY);this.yn=(0,_.Za)();a=this.uc=EW(b,this.gt);var c=FW("hoverDelay",a);this.sf?this.sf.Nu&&
(window.clearTimeout(this.ig),this.ig=window.setTimeout((0,_.J)(this.jB,this,b),c-FW("loadDelay",a))):NW(this)}}};_.h.tA=function(a){this.cB=(0,_.Za)();if("blur"!=a.type||a.target==this.kj||a.target==this.Rd){if(a=a.relatedTarget||a.toElement){if("IFRAME"==a.tagName)return;if(this.dB)for(;a&&"BODY"!=a.tagName;){if(a==this.dB)return;a=a.parentNode}}HW(this)}};_.h.qu=function(){HW(this,0)};_.h.xU=function(a){this.Sl.x=a.clientX;this.Sl.y=a.clientY};
var NW=function(a){a.ig&&(window.clearTimeout(a.ig),a.ig=null);if(a.Rd&&(a.Qe(a.Rd,{type:"hover",config:a.uc}),!a.sf)){var b=a.sf=new GW(a);nW((0,_.J)(function(c){c.iC("card",OW++,b.Re)&&b.load(this.uc)},a))}};
JW.prototype.jB=function(a){this.ig&&(window.clearTimeout(this.ig),this.ig=null);if(this.Rd==a){var b=FW("hoverDelay",this.uc)-FW("loadDelay",this.uc)-(0,_.Za)()+this.yn;if(0<b)this.ig=window.setTimeout((0,_.J)(this.jB,this,a),b);else{this.Qe(a,{type:"hover",config:this.uc});this.uc.feedbackHandler||(this.uc.feedbackHandler=this.u_);this.uc.overrideFeedback=!0;this.uc.scheduleEventHandler&&(this.uc.overrideCalendar=!0);this.uc.sendChatHandler&&(this.uc.overrideChat=!0);this.uc.sendEmailHandler&&(this.uc.overrideEmail=
!0);this.uc.videoChatHandler&&(this.uc.overrideVideoChat=!0);b=this.sf;var c=this.uc;a=(0,_.J)(this.bM,this,a);b.Nu&&(b.rW=a,c.ri=++b.jJ,b.Ga.send("loadData",c,void 0,_.Hl))}}};
JW.prototype.u_=function(){var a={};a={apiKey:a.apiKey||a.apiKey,environment:a.e$||a.environment,helpCenterPath:a.O$||a.helpCenterPath,locale:a.locale||a.locale||"en".replace(/-/g,"_"),nonce:a.nonce||a.nonce,productData:a.productData||a.productData,receiverUri:a.raa||a.receiverUri,renderApiUri:a.zaa||a.renderApiUri,theme:a.Xaa||a.theme,window:a.window||a.window};a=sW(vW,"help.service.Lazy.create","5003140",a);(new uW(a)).t_({productVersion:"gapi",customZIndex:2000000002})};
JW.prototype.bM=function(a){if(this.Rd===a&&this.sf&&this.sf.Nu&&this.yn){var b=FW("hoverDelay",this.uc)-(0,_.Za)()+this.yn;0<b?window.setTimeout((0,_.J)(this.bM,this,a),b):(this.DA(),this.kj=this.Rd,this.fh=this.uc,LW(this,this.Rd,"mousemove"),this.yn=this.uc=this.Rd=null,oW().oD(this.sf.Re))}};
var HW=function(a,b){a.Rd&&LW(a,a.Rd,"mousemove");a.Rd=null;a.uc=null;a.yn=null;a.ig&&(window.clearTimeout(a.ig),a.ig=null);!a.Gh&&a.kj&&(a.Gh=window.setTimeout((0,_.J)(a.DA,a),"number"===typeof b?b:FW("closeDelay",a.fh)))};JW.prototype.DA=function(){this.Gh&&(window.clearTimeout(this.Gh),this.Gh=null);this.kj&&oW().yq(this.sf.Re)};var IW=function(a,b){a.Qe(null,b);a.TB&&a.TB.send("cardAction",b,void 0,a.SB)};
JW.prototype.jy=function(a,b,c){var d={};d.frame=a;d.filter=b||_.Dl;d.callback=c||_.hb;this.OF.set(String(_.Zc(a)),d);a.register("cardAction",(0,_.J)(function(e){IW(this,e);d.callback(e)},this),d.filter)};JW.prototype.ly=function(a){this.SB=a||_.Dl;_.$k.Aj((0,_.J)(function(b){this.TB=b;this.TB.register("cardAction",(0,_.J)(this.Vs,this),this.SB)},this),void 0,this.SB)};
JW.prototype.Vs=function(a){this.OF.forEach(function(b){return b.frame.send("cardAction",a,void 0,b.filter)});this.sf&&this.sf.Ga.send("cardAction",a,void 0,_.Hl)};var OW=0;
_.PW=function(){var a={},b=new JW,c=new xW;a.hs=function(d,e,f){b.hs(d,e,f)};a.LD=function(d){b.LD(d)};a.Sd=function(d){b.Sd(d)};a.dm=function(d){b.dm(d)};a.jy=function(d,e,f){b.jy(d,e,f)};a.ly=function(d){b.ly(d)};a.Vs=function(d){b.Vs(d)};a.wa=function(d,e){e.origin=window.location.protocol+"//"+window.location.host;var f=_.$k.Ph({url:":card",where:document.getElementById(d),queryParams:e,messageHandlers:{_ready:function(){f.send("loadData",e,void 0,_.Hl)},loaded:function(){f.send("render",void 0,
void 0,_.Hl)}},messageHandlersFilter:_.Hl})};a.BI=function(){c.BI()};a.IA=function(d,e,f){c.IA(d,e,f)};a.JA=function(d,e,f,g){c.JA(d,e,f,g)};a.KA=function(d){c.KA(d)};a.zV=function(d,e,f){c.Aj(d,e,f)};a.BV=function(){return _.Hl};a.CV=function(){return _.Dl};return a}();
_.y("gapi.card.watch",_.PW.hs);_.y("gapi.card.unwatch",_.PW.LD);_.y("gapi.card.addCallback",_.PW.Sd);_.y("gapi.card.removeCallback",_.PW.dm);_.y("gapi.card.render",_.PW.wa);_.y("gapi.card.connectChild",_.PW.jy);_.y("gapi.card.connectOpener",_.PW.ly);_.y("gapi.card.broadcast",_.PW.Vs);_.y("gapi.card.iframeClose",_.PW.close);_.y("gapi.card.iframeRestyle",_.PW.IA);_.y("gapi.card.iframeSend",_.PW.JA);_.y("gapi.card.iframeSetup",_.PW.KA);_.y("gapi.card.iframeAddOnOpenerHandler",_.PW.zV);
_.y("gapi.card.iframeGetCrossOriginFilter",_.PW.BV);_.y("gapi.card.iframeGetSameOriginFilter",_.PW.CV);

});
// Google Inc.
