name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: |
          cd lab8_final
          mvn --batch-mode --update-snapshots verify
          mkdir staging
          cp src/main/java/Client/target/lab8-client-jar-with-dependencies.jar staging
          cp src/main/java/Server/target/lab8-server-jar-with-dependencies.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: lab8_final/staging/*
          retention-days: 1
  create_release:
    name: "Prelease"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            lab8_final/staging/lab8-client-jar-with-dependencies.jar
            lab8_final/staging/lab8-server-jar-with-dependencies.jar
